def generate_label(score: float) -> dict:
    """Maps a confidence score to a transparency label dict with three fields."""
    pct = round(score * 100)

    if score >= 0.85:
        return {
            "classification": "AI-Generated Content",
            "confidence_display": f"{pct}% AI likelihood",
            "disclosure": (
                "This submission was analyzed by Provenance Guard. Multiple "
                "independent signals — including statistical predictability, "
                "sentence structure uniformity, vocabulary compression, and "
                "language model marker phrases — converged to indicate this "
                "text was likely generated by an AI system. This label does "
                "not constitute a final determination. The author may submit "
                "an appeal if this classification is incorrect."
            ),
        }
    if score >= 0.65:
        return {
            "classification": "Likely AI-Generated",
            "confidence_display": f"{pct}% AI likelihood",
            "disclosure": (
                "This submission was analyzed by Provenance Guard. The "
                "detection signals lean toward AI generation, though not with "
                "high confidence. Patterns such as predictable phrasing, "
                "uniform structure, or AI-characteristic vocabulary were "
                "detected. The author may submit an appeal if this "
                "classification is incorrect."
            ),
        }
    if score >= 0.36:
        return {
            "classification": "Authorship Uncertain",
            "confidence_display": f"Inconclusive ({pct}% AI likelihood)",
            "disclosure": (
                "This submission was analyzed by Provenance Guard. The "
                "detection signals produced mixed results and the system "
                "cannot confidently attribute this text to a human or AI "
                "author. This may indicate a hybrid workflow, heavily edited "
                "AI output, or content that falls outside the system's "
                "reliable detection range. The author may submit additional "
                "context via an appeal."
            ),
        }
    if score >= 0.16:
        return {
            "classification": "Likely Human-Authored",
            "confidence_display": f"{100 - pct}% human likelihood",
            "disclosure": (
                "This submission was analyzed by Provenance Guard. The text "
                "shows patterns consistent with human authorship — including "
                "variable sentence rhythm, diverse vocabulary, and low "
                "reliance on AI-characteristic phrasing. This label does not "
                "constitute a final determination."
            ),
        }
    return {
        "classification": "Human-Authored Content",
        "confidence_display": f"{100 - pct}% human likelihood",
        "disclosure": (
            "This submission was analyzed by Provenance Guard. The text "
            "shows strong patterns consistent with human authorship — "
            "including variable sentence rhythm, diverse vocabulary, and "
            "an absence of AI-characteristic phrasing. This label does not "
            "constitute a final determination."
        ),
    }
